# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: b1e5f13
_src_path: ./
accountname: quickplates
description: Flux manifests example ☸️
docs: true
docsurl: https://quickplates.github.io/flux-example
projectname: flux-example
reponame: flux-example
repourl: https://github.com/quickplates/flux-example
